### PR TITLE
validation and tests

### PR DESCRIPTION
**Pull request by mosetf**
incooparate validation on server side and write tests for authentication and database setup

### CODE REVIEW

**Comment by sh-Enoch** [comment]
kindly create a requirements.txt to help install dependency packages

**Comment by sh-Enoch** [comment]
@mosetf  suggesting we validate the email using the email_validator module rather than hard coding it

**Comment by mosetf** [comment]
@sh-Enoch i have added your suggestions that is requirements.txt file and created a virtual enviro
nment

**Comment by Ivy-Chelsea** [comment]
@mosetf i can't see the requirements.txt file, it's in which directory? Or you haven't pushed the changes yet?

**Pull request merged**
